-- AlterTable
ALTER TABLE "comments" ALTER COLUMN "nivel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "comment_like" SET DEFAULT 0,
ALTER COLUMN "comment_like" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "comment_dislike" SET DEFAULT 0,
ALTER COLUMN "comment_dislike" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "marketingpublications" ALTER COLUMN "conditions" SET DATA TYPE TEXT,
ALTER COLUMN "clicks" SET DEFAULT 0,
ALTER COLUMN "clicks" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "posts" ALTER COLUMN "post_like" SET DEFAULT 0,
ALTER COLUMN "post_like" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "post_dislike" SET DEFAULT 0,
ALTER COLUMN "post_dislike" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "views" SET DEFAULT 0,
ALTER COLUMN "views" SET DATA TYPE DOUBLE PRECISION;
